# yaml-language-server: $schema=https://json.schemastore.org/dependabot-2.0.json
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "gomod"
    directory: "/"
    allow:
      - dependency-type: all
    schedule:
      interval: "weekly"
  - package-ecosystem: "gomod"
    directory: "/tools/"
    allow:
      - dependency-type: direct
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "[tools]"
    groups:
      all-tools:
        patterns:
          - "*"
