# yaml-language-server: $schema=https://golangci-lint.run/jsonschema/golangci.jsonschema.json

# https://golangci-lint.run/usage/configuration/
# https://golangci-lint.run/usage/linters/

version: "2"

run:
  go: "1.23"
  modules-download-mode: readonly
  issues-exit-code: 1
  tests: true

output:
  formats:
    text:
      path: stderr
      print-linter-name: true
      print-issued-lines: true

linters:
  default: all
  disable:
    - nlreturn
    - wsl
    - lll
    - wrapcheck
    - varnamelen
    - nonamedreturns
    - testpackage
    - funlen
    - cyclop
    - exhaustive
    - exhaustruct # TODO: reconsider
    - depguard    # TODO: reconsider
    - godox       # TODO: reconsider
    - funcorder
    - wsl
    - wsl_v5
    - noinlineerr

  settings:
    # https://golangci-lint.run/usage/linters/#unused
    unused:
      field-writes-are-uses: false
      post-statements-are-reads: false
      exported-fields-are-used: true
      parameters-are-used: true
      local-variables-are-used: false
      generated-is-used: true

    # https://golangci-lint.run/usage/linters/#tagliatelle
    tagliatelle:
      case:
        use-field-name: true
        rules:
          json: snake
          yaml: camel
          xml: camel
          bson: camel
          avro: snake
          mapstructure: kebab

    # https://golangci-lint.run/usage/linters/#paralleltest
    paralleltest:
      ignore-missing: true
      ignore-missing-subtests: true

    # https://golangci-lint.run/usage/linters/#nolintlint
    nolintlint:
      allow-unused: true

    # https://golangci-lint.run/usage/linters/#gocyclo
    gocyclo:
      min-complexity: 40

    # https://golangci-lint.run/usage/linters/#maintidx
    maintidx:
      under: 10

    # https://golangci-lint.run/usage/linters/#govet
    govet:
      enable-all: true
      settings:
        shadow:
            strict: false
      #disable:
      #  - fieldalignment

    # https://golangci-lint.run/usage/linters/#prealloc
    prealloc:
      simple: true
      range-loops: true
      for-loops: true

    # https://golangci-lint.run/usage/linters/#revive
    # https://github.com/mgechev/revive/blob/HEAD/RULES_DESCRIPTIONS.md
    revive:
      rules:
        - name: unused-parameter
          disabled: true



  exclusions:
    generated: lax
    presets:
      - comments
      - std-error-handling
      - common-false-positives
    rules:
      - path: 'error_test.go'
        linters: [thelper, errorlint]
      - path: _test\.go
        linters: [gochecknoglobals, goconst, goerr113, mnd, dupl, maintidx, gocyclo, err113]
      - path: _test\.go
        linters:
          - govet
        text: 'fieldalignment:'
      - path: _test\.go
        linters:
          - revive
        text: 'unused-parameter:'
      - path: _test\.go
        linters:
          - revive
        text: 'context-as-argument:'
      - path: internal/tesatingx/testdata
        linters: [gochecknoglobals, goconst, goerr113, mnd, dupl, maintidx]


# https://golangci-lint.run/usage/configuration/#fmt
# https://golangci-lint.run/usage/formatters/
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
    # - golines
