# yaml-language-server: $schema=https://golangci-lint.run/jsonschema/golangci.jsonschema.json

# https://golangci-lint.run/usage/configuration/
# https://golangci-lint.run/usage/linters/

run:
  concurrency: 0
  go: '1.22'
  timeout: 10m
  issues-exit-code: 1
  tests: true
  modules-download-mode: readonly

output:
  formats:
    - format: colored-line-number
      path: stderr
  print-issued-lines: true
  print-linter-name: true

linters:
  enable-all: true
  disable:
    - exportloopref # deprecated
    - nlreturn
    - wsl
    - lll
    - wrapcheck
    - varnamelen
    - nonamedreturns
    - testpackage
    - funlen
    - cyclop
    - exhaustive
    - exhaustruct # TODO: reconsider
    - depguard    # TODO: reconsider
    - godox       # TODO: reconsider

issues:
  # https://golangci-lint.run/usage/false-positives/#default-exclusions
  exclude-use-default: true
  exclude-dirs-use-default: true
  include:
    - EXC0004
    - EXC0005
    - EXC0006
  exclude-rules:
    - path: 'error_test.go'
      linters: [thelper, errorlint]
    - path: '(.+)_test\.go'
      linters: [gochecknoglobals, goconst, goerr113, mnd, dupl, maintidx, gocyclo, err113]
    # Exclude govet fieldalignment in tests.
    - path: '(.+)_test\.go'
      linters: [govet]
      text: 'fieldalignment:'
    - path: internal/tesatingx/testdata
      linters: [gochecknoglobals, goconst, goerr113, mnd, dupl, maintidx]

linters-settings:

  # https://golangci-lint.run/usage/linters/#unused
  unused:
    field-writes-are-uses: false
    post-statements-are-reads: false
    exported-fields-are-used: true
    parameters-are-used: true
    local-variables-are-used: false
    generated-is-used: true

  # https://golangci-lint.run/usage/linters/#tagliatelle
  tagliatelle:
    case:
      use-field-name: true
      rules:
        json: snake
        yaml: camel
        xml: camel
        bson: camel
        avro: snake
        mapstructure: kebab

  # https://golangci-lint.run/usage/linters/#paralleltest
  paralleltest:
    ignore-missing: true
    ignore-missing-subtests: true

  # https://golangci-lint.run/usage/linters/#nolintlint
  nolintlint:
    allow-unused: true

  # https://golangci-lint.run/usage/linters/#cyclop
  cyclop:
    max-complexity: 10
    package-average: 0.5
    skip-tests: true

  # https://golangci-lint.run/usage/linters/#gocyclo
  gocyclo:
    min-complexity: 40

  # https://golangci-lint.run/usage/linters/#maintidx
  maintidx:
    under: 10

  # https://golangci-lint.run/usage/linters/#govet
  govet:
    enable-all: true
    settings:
      shadow:
          strict: false
    #disable:
    #  - fieldalignment

  # https://golangci-lint.run/usage/linters/#misspell
  misspell:
    ignore-words:
      - ""
    locale: US

  # https://golangci-lint.run/usage/linters/#prealloc
  prealloc:
    simple: true
    range-loops: true
    for-loops: true

  # https://golangci-lint.run/usage/linters/#gofumpt
  gofumpt:
    module-path: github.com/moukoublen/pick
    extra-rules: true
