# yaml-language-server: $schema=https://json.schemastore.org/codecov.json
# curl --data-binary @codecov.yml https://codecov.io/validate

codecov:
  strict_yaml_branch: default  # only use the latest YAML on stated branch

ignore:
  - "internal/testingx" # test helpers

# https://docs.codecov.com/docs/pull-request-comments
comment:
  layout: "condensed_header, condensed_files, condensed_footer"
  behavior: default
  require_changes: false      # Post comment even if there's no change in coverage
  require_base: false         # [true :: must have a base report to post]
  require_head: true           # [true :: must have a head report to post]
  hide_project_coverage: false # [true :: only show coverage on the git diff]
