# yaml-language-server: $schema=https://json.schemastore.org/codecov
# curl --data-binary @codecov.yml https://codecov.io/validate

codecov:
  strict_yaml_branch: default  # only use the latest YAML on stated branch

ignore:
  - "internal/testingx" # test helpers

comment: false
