#!/usr/bin/env sh

set -e

# https://git-scm.com/docs/git-status

if ! git diff --exit-code >/dev/null; then
  echo ""
  echo "**New or modified files**"
  echo ""

  git status --short --branch --untracked-files=all --ahead-behind
  exit 1
fi
