#!/usr/bin/env bash

set -e
#set -u
set -o pipefail

tmp_dir() {
  local name="${1}"
  local tmp_path=""
  case "$(uname)" in
    "Darwin")
      tmp_path="$(mktemp -d -t "${name}")"
      ;;
    "Linux")
      tmp_path="$(mktemp --directory --tmpdir "${name}_XXXXXXX")"
      ;;
    *)
      tmp_path="/tmp/${name}_install"
      mkdir -p "${tmp_path}"
      ;;
  esac
  echo "${tmp_path}"
}


get_latest_version() {
  JS_BODY=$(curl --silent --fail --location "https://api.github.com/repos/koalaman/shellcheck/releases/latest")
  echo "${JS_BODY}" | jq '.tag_name' --raw-output
}

package_os() {
  case "$(uname)" in
    "Darwin")
      echo "darwin"
      ;;
    "Linux")
      echo "linux"
      ;;
  esac
}

package_arch() {
  local arch
  arch="$(uname -m | tr '[:upper:]' '[:lower:]')"
  case "${arch}" in
    "x86_64")
      echo "x86_64"
      ;;
    "aarch64")
      echo "aarch64"
      ;;
    "arm64")
      echo "aarch64"
      ;;
  esac
}

VERBOSE=""
VERSION=""
DESTINATION_DIR=""
UNKNOWN_ARGS=()
while (($#)); do
  case "${1}" in
    -v | --version)
      VERSION="${2}"
      shift 2
      ;;
    -d | --destination)
      DESTINATION_DIR="${2}"
      shift 2
      ;;
    --verbose)
      VERBOSE="1"
      shift 1
      ;;
    *)
      UNKNOWN_ARGS+=("${1}")
      shift
      ;;
  esac
done

if [[ ${VERSION} == "" ]]; then
  VERSION="$(get_latest_version)"
fi

if [[ ${DESTINATION_DIR} == "" ]]; then
  echo "missing destination argument"
  exit 1
fi

TMP_DIR="$(tmp_dir 'shellcheck')"
trap "rm -rf ${TMP_DIR} || true" EXIT

DL_URL="https://github.com/koalaman/shellcheck/releases/download/${VERSION}/shellcheck-${VERSION}.$(package_os).$(package_arch).tar.xz"

curl \
  --silent \
  --fail \
  --location \
  "${DL_URL}" \
  -o "${TMP_DIR}/shellcheck.tar.xz"

tar \
  --extract \
  --xz \
  --file="${TMP_DIR}/shellcheck.tar.xz" \
  --strip-components=1 \
  --directory="${TMP_DIR}"

install -m 755 "${TMP_DIR}"/shellcheck "${DESTINATION_DIR}"

# to update all dates in order for make file to get it as new (check stat "${DESTINATION_DIR}/shellcheck")
touch "${DESTINATION_DIR}/shellcheck"
