#!/usr/bin/env bash

if ! command -v shfmt &>/dev/null; then
  echo 'shfmt not found' >&2
  exit 1
fi

./scripts/foreach-script shfmt \
  --simplify \
  --language-dialect auto \
  --case-indent \
  --indent 2 \
  --write
