# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Benchmarks

on:
  pull_request:
    branches: [ main ]

jobs:

  lint-and-test:
    name: Benchmarks
    runs-on: ubuntu-latest
    env:
      BENCH_DIR: /tmp/bench
    steps:

    # https://github.com/actions/setup-go
    - name: set up go
      uses: actions/setup-go@v5
      with:
        go-version: "1.23.x"
        check-latest: true
        cache: false

    - name: Initialize
      run: |
        go install golang.org/x/perf/cmd/benchstat@latest
        rm -rf ${{ env.BENCH_DIR }}
        mkdir -p ${{ env.BENCH_DIR }}

    # https://github.com/actions/checkout
    - uses: actions/checkout@v4
      name: Checkout main
      with:
        ref: main

    - name: Benchmark main
      run: |
        rm -rf ${{ env.BENCH_DIR }}/bench.main.txt
        make ci-bench | tee ${{ env.BENCH_DIR }}/bench.main.txt

    # https://github.com/actions/checkout
    - uses: actions/checkout@v4
      name: Checkout pull request HEAD

    - name: Benchmark pull request head
      run: |
        rm -rf ${{ env.BENCH_DIR }}/bench.head.txt
        make ci-bench | tee ${{ env.BENCH_DIR }}/bench.head.txt

    - name: Compare benchmarks
      run: |
        benchstat ${{ env.BENCH_DIR }}/bench.main.txt ${{ env.BENCH_DIR }}/bench.head.txt | tee ${{ env.BENCH_DIR }}/summary.txt
        echo '# Benchmarks stats' >> $GITHUB_STEP_SUMMARY
        echo '```' >> $GITHUB_STEP_SUMMARY
        cat ${{ env.BENCH_DIR }}/summary.txt >> $GITHUB_STEP_SUMMARY
        echo '```' >> $GITHUB_STEP_SUMMARY
