name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  lint-and-test:
    name: Lints and Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [ '1.21', '1.22', '1.23' ]
    steps:

    # https://github.com/actions/checkout
    - uses: actions/checkout@v4

    # https://github.com/actions/setup-go
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go-version }}
        check-latest: true
        cache: false

    # https://github.com/actions/cache
    - name: Cache Tools
      id: cache-tools
      uses: actions/cache@v4
      with:
        path: |
          .tools/
          ~/.cache/go-build
          ~/go/pkg
        key: ci-tools-${{ runner.os }}-${{ runner.arch }}-${{ matrix.go-version }}-${{ hashFiles('**/go.mod', '**/go.sum', '**/Makefile', '.github/workflows/ci.yml') }}
        restore-keys: |
          ci-tools-${{ runner.os }}-${{ runner.arch }}-${{ matrix.go-version }}

    - name: Install Tools
      # if: steps.cache-tools.outputs.cache-hit != 'true'
      run: make tools

    - name: go mod verify
      run: go mod verify

    - name: version of make
      run: make --version

    - name: env
      run: make env

    - name: gofumpt
      run: make gofumpt

    - name: goimports
      run: make goimports

    - name: staticcheck
      run: make staticcheck

    - name: golangci-lint
      run: make golangci-lint-github-actions

    - name: Test
      run: make test

    # https://github.com/codecov/codecov-action
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v4
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      if: matrix.go-version == '1.23'
