# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  lints:
    name: Lints
    runs-on: ubuntu-latest
    steps:

    # https://github.com/actions/checkout
    - uses: actions/checkout@v7

    - uses: jdx/mise-action@v4.2.3
      with:
        install: true # [default: true] run `mise install`
        cache: true # [default: true] cache mise using GitHub's cache
        experimental: false # [default: false] enable experimental features
        log_level: debug # [default: info] log level
        cache_key: "mise-{{platform}}-{{install_args_hash}}-{{file_hash}}"


    # https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/workflow-commands-for-github-actions
    # https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/workflow-commands-for-github-actions#environment-files
    - id: go_version
      name: Get Go version
      run: |
        GO_VER=$(go env GOVERSION | cut -d. -f1-2)
        echo "Detected Go version: ${GO_VER}"
        echo "GO_VER=${GO_VER}" >> "$GITHUB_OUTPUT"

        GOCACHE=$(go env GOCACHE)
        echo "Detected GOCACHE: ${GOCACHE}"
        echo "GOCACHE=${GOCACHE}" >> "$GITHUB_OUTPUT"

        GOPATH=$(go env GOPATH)
        echo "Detected GOPATH: ${GOPATH}"
        echo "GOPATH=${GOPATH}" >> "$GITHUB_OUTPUT"


    # https://github.com/actions/cache
    - name: cache go deps
      id: cache-go
      uses: actions/cache@v6
      with:
        path: |
          ${{ steps.go_version.outputs.GOCACHE }}
          ${{ steps.go_version.outputs.GOPATH }}
        key: ci-go-${{ runner.os }}-${{ runner.arch }}-${{ hashFiles('**/go.mod', '**/go.sum', '.github/workflows/ci.yml') }}
        restore-keys: |
          ci-go-${{ runner.os }}-${{ runner.arch }}-

    - name: env
      run: |
        make --version
        echo ""
        make env

    - name: check shell files
      run: make ci-sh

    - name: make mod
      run: make ci-mod

    - name: format and check
      run: make ci-format

    - name: golangci-lint
      run: make golangci-lint

  tests:
    name: Tests
    strategy:
      matrix:
        go-version: [ '1.25', '1.26' ]
        os: ['ubuntu-latest']
        include:
          - os: 'ubuntu-latest'
            go-version: '1.26'
            cover: true

    runs-on: "${{ matrix.os }}"
    steps:
      # https://github.com/actions/checkout
    - uses: actions/checkout@v7

    # https://github.com/actions/setup-go
    - name: set up go
      uses: actions/setup-go@v7
      with:
        go-version: "${{ matrix.go-version }}.x"
        check-latest: true
        cache: false

    - name: test
      run: |
        go test -timeout 30s ./...
      if: ${{ !matrix.cover }}

    - name: test with cover and race
      run: |
        go test -timeout 30s -race -coverprofile=coverage.txt -covermode=atomic ./...
      if: ${{ matrix.cover }}

    # https://github.com/codecov/codecov-action
    - name: upload coverage reports to codecov
      uses: codecov/codecov-action@v7
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      if: ${{ matrix.cover }}
